# Generated by Django 3.2.4 on 2021-07-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklint', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='rate',
            new_name='price',
        ),
    ]
