# Generated by Django 3.2.4 on 2021-07-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklint', '0006_alter_cartproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
