# Generated by Django 3.2.4 on 2021-07-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklint', '0007_alter_cartproduct_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
